---
# tasks file for test_lininfile
- name: print var
  debug:
    var:  thefile_name
  tags:
    - alle
- name: create a line if no filter present
  lineinfile:
    path: "{{ thefile_name }}"
    regex: 'filter_users =.*'
    line: "filter_users = "
    create: yes
    owner: muelmar
    group: muelmar
    mode: 0440
    #validate: "visudo -cf  %s"
    validate: "ls -l   %s"
- name: Add a line to a file if the file does not exist
  lineinfile:
    path: "{{ thefile_name }}"
    regex: '^(filter_users *=.*)$' 
    line: '\1 {{ filer_users | join(",") }}'
    backrefs: yes
  notify: restart sshd
     
  tags: 
    - alle
    - einzeln
