---
# tasks file for test_lininfile
- name: print var
  debug:
    var:  thefile_name
- name: Add a line to a file if the file does not exist, without passing regexp
  lineinfile:
    path: "{{ thefile_name }}"
    line: 192.168.1.99 foo.lab.net foo
    create: yes
