---
- hosts: all
  become: yes
  roles:
    - role: docker
      tags:
        - docker
    - role: adguard
      tags:
        - adguard
    - role: update_all_packages
      tags:
        - update_all_packages


