---
- name: create user to test the user module
  hosts: turtle
  become: True
  tasks:
    - name: create users
      ansible.builtin.user:
        name: ansible_test
        shell: /bin/bash
        comment: "Kann geloescht werden"
        generate_ssh_key: false
        group:  users
        remove:  True
        password:  '!!'
        state: absent
    - name: create group
      ansible.builtin.group:
        name: ansible_test
        state: absent

