---
# tasks file for packages installs packages according to host_vars
#
- name: Install essential packages
  ansible.builtin.package:
    name:
      - "{{ item }}" 
    state: present
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item }}"
########
- name: remove unwanted
  ansible.builtin.package:
    name:  "{{ item }}"
    state: absent
  loop: "{{ unwanted }}"
  loop_control:
    label: "{{ item }}"
