---
# tasks file for update_all_pakages
- name: Update for Debian ubuntu Mint
  apt:
    upgrade: full
    update_cache: yes
  when:   ansible_os_family == "Debian"
- name: upgrade all packages RedHat
  yum:
    name: "*"
    state: latest
  when:   ansible_os_family == "RedHat"
- name: Check if reboot is needed
  ansible.builtin.stat:
    path:  /var/run/reboot-required
  register: reboot_needed
- name: print if needed
  ansible.builtin.debug:
    msg: "A reboot is needed"
  when: reboot_needed.stat.exists
