---
# tasks file for bvs
- name: create groups bvs
  ansible.builtin.group:
    name: "bvs"
    state: present
    gid: 1234
      #
- name: create logical volume
  lvol:
    vg: "{{ bvs_vgname | default('vgroot') }}"
    lv: "lvbvs"
    size: "{{ bvs_lvsize | default('10G') }}"
    resizefs: True
    state: present
      #
- name: "make filesystem"
  filesystem:
    fstype: "{{ bvs_fstype | default('ext4') }}"
    dev: "/dev/{{ bvs_vgname | default('vgroot') }}/lvbvs"
      #
- name: mount into /home 
  ansible.posix.mount:
    path: "/home/bvs"
    src:  "/dev/{{ bvs_vgname | default('vgroot') }}/lvbvs"
    fstype: "{{ bvs_fstype | default('ext4') }}"
    opts: "defaults"
    state: mounted

 ############################
- name: create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    home: "/home/bvs/{{ item.name }}"
    shell: /bin/bash
    comment: "{{ item.name }}"
    generate_ssh_key: true
    create_home: true
    group:  "bvs"
    uid:  "{{ item.uid }}"
    umask: 0002
    skeleton: /etc/skel
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
      ##
- name:  Whe need umask 0002 in .bashrc
  lineinfile:
    path: "/home/bvs/{{ item.name }}/.bashrc"
    line: "umask 0002"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"


